#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )"

for f in .hgrc .bash_aliases .bashrc .bash_profile .bash_functions .Xdefaults .screenrc .gitconfig
do
    ln -s "$DIR/$f" ~
done

PLATFORM=`uname -o 2> /dev/null || uname -s`
if [ $PLATFORM == "Cygwin" ]; then
    ln -s "$DIR/.startxwinrc" ~
fi
