#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )"

for f in .hgrc .bash_aliases .bashrc .bash_profile .Xdefaults .screenrc .gitconfig
do
    ln -s "$DIR/$f" ~
done

if [ `uname -o 2> /dev/null || uname -s` = "Cygwin" ]; then
    ln -s "$DIR/.startxwinrc" ~
fi

# Adding ~/.bin directory
mkdir -p ~/.bin
